

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - NODE_ENV=development
  #     - REDIS_URL=redis://redis:6379  # Connection URL for Redis
  #   depends_on:
  #     - redis
  #   command: ["bun", "dev", "src/index.ts"]

volumes:
  redis_data: